databases:
  - name: dpg-cgtf8mo2qv2fde8o0kig-a
    databaseName: budget_a161
    user: budget_a161_user

services:
  - type: web
    name: Budgetron
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_a161
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false